#!/bin/bash
#Austin Pennington
#Script that gets listing data using price as a parameter

curl https://api.mercadolibre.com/sites | sed -e 's/,/\'$'\n/g' | grep id | tr -d '"' | tr -d '{id:' | tr -d '[' > siteList

#loop through site ids
#SID is every line in siteList, i.e. site ID

#usage
if [ "$#" -ne 1 ]
then
        echo "Usage: script | price(e.g. 1)"
else

	while read SID; do
		curl -X GET https://api.mercadolibre.com/sites/$SID/listing_prices?price=$1 | jq . > listingPrices$SID

	done < siteList
fi
