#!/bin/bash
#Austin Pennington
#Columbia University
#
#For curling and parsing items in a category
#usage: script URL outputFileName
if [ "$#" -ne 2 ]
then
        echo "Usage: script | siteID |  categoryID"
        echo "E.g.:  ./curlNparseScript MLA MLA5726"
else
        curl -s "https://api.mercadolibre.com/sites/$1/search?category=$2" | sed -e 's/"id":"'$1'/\'$'\n\t"id":"'$1'/g' | sed -e 's/{/\'$'\n/g' | sed -e 's/,/\'$'\n/g' | grep 'total'

fi
